package com.opencode.android.ui.session

import com.opencode.android.domain.Message
import com.opencode.android.domain.MessageInfo
import com.opencode.android.domain.MessageTime
import com.opencode.android.domain.Part

/**
 * Candidate 1 strangler: the optimistic-echo part of the send path.
 *
 * `performSend` shows the user's turn immediately (prompt_async only returns
 * 204 and the persisted message arrives a round-trip later), so the visible
 * text and the placeholder row are built before any IO. Both are pure and
 * pinned by tests here.
 */

/**
 * The text shown in the conversation row: the prompt plus an `[Attached: name]`
 * marker per attachment. The marker is display-only — the wire body uses the
 * uploaded file paths instead.
 */
fun buildDisplayText(rawText: String, attachmentNames: List<String>): String = buildString {
    append(rawText)
    for (name in attachmentNames) {
        if (isNotEmpty()) append("\n")
        append("[Attached: $name]")
    }
}.trim()

/**
 * The local placeholder row for a just-sent turn. [messageId] is generated by
 * the caller (the `local:` prefix lets the next refresh recognise and replace
 * it with the server row).
 */
fun buildOptimisticEcho(
    sessionId: String,
    messageId: String,
    displayText: String,
    createdAt: Long,
): Message = Message(
    id = messageId,
    sessionId = sessionId,
    role = "user",
    parts = listOf(Part(type = "text", text = displayText)),
    time = MessageTime(created = createdAt),
    info = MessageInfo(role = "user"),
)
